Mvc-Projem/Models/Admin.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Mvc_Projem.Models
{
    public class Admin
    {
        [Key]
        public int AdminID { get; set; }

        [Column(TypeName = "Varchar(20)")]
        public string Kullanici { get; set; }


        [Column(TypeName = "Varchar(20)")]
        public string Sifre { get; set; }
    }

}

Mvc-Projem/Models/Birim.cs
using System.ComponentModel.DataAnnotations;

namespace Mvc_Projem.Models
{
    public class Birim
    {
        [Key]
        public int Id { get; set; }
        public string BirimAd { get; set; }
        public IList<Personel> Personels { get; set; } // bir birimin birden fazla personeli olabilir.
    }
}

Mvc-Projem/Models/Context.cs
using Microsoft.EntityFrameworkCore;

namespace Mvc_Projem.Models
{
    public class Context : DbContext
    {
        public DbSet<Birim> Birims { get; set; }
        public DbSet<Personel> Personels { get; set; }
        public DbSet<Admin> Admins { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server =.; Database = BirimDB; Trusted_Connection = True; MultipleActiveResultSets = true; TrustServerCertificate = True;");
        }
    }
}

Mvc-Projem/Models/ErrorViewModel.cs
namespace Mvc_Projem.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Mvc-Projem/Models/Personel.cs
using System.ComponentModel.DataAnnotations;

namespace Mvc_Projem.Models
{
    public class Personel
    {
        [Key]
        public int PersonelId { get; set; } // PK
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Sehir { get; set; }


        public int BirimId { get; set; } // FK
        public Birim Birim { get; set; } // bir personelin bir birimi olur.

    }
}

Mvc-Projem/Controllers/BirimController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Mvc_Projem.Models;

namespace Mvc_Projem.Controllers
{
    public class BirimController : Controller
    {
        Context context = new Context();

        [Authorize] // yetkisi olanlar giris yapıcak!
        public IActionResult Index()
        {
            var degerler = context.Birims.ToList();

            return View(degerler);
        }

        [HttpGet] // sayfa yuklendiğinde çalışıcak.
        public IActionResult YeniBirim()
        {
            return View();
        }

        [HttpPost] // sayfada post işlemi oldugunda çalışıcak
        public IActionResult YeniBirim(Birim birim)
        {
            context.Birims.Add(birim);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult BirimSil(int id) // silme işlemini görmüyor.
        {
            var sil = context.Birims.Find(id);
            context.Birims.Remove(sil);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult BirimGetir(int id)
        {
            var birim = context.Birims.Find(id);
            return View("BirimGetir", birim);
        }

        public IActionResult BirimGuncelle(Birim birim)
        {
            var dep = context.Birims.Find(birim.Id);

            dep.BirimAd = birim.BirimAd;
            context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult BirimDetay(int id) // Birime ait personeller (a kişisi b biriminde gibi)
        {
            var degerler = context.Personels.Where(x => x.BirimId == id).ToList(); // amac Detaya tıklandıgında o birime ait personelleri listelesin.

            var birimAd = context.Birims.Where(x => x.Id == id).Select(y => y.BirimAd).FirstOrDefault(); // ilgili birimin adını getirme.
            ViewBag.brm = birimAd;
            return View(degerler);
        }

    }
}

Mvc-Projem/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Mvc_Projem.Models;
using System.Diagnostics;

namespace Mvc_Projem.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Mvc-Projem/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Mvc_Projem.Models;
using System.Security.Claims;

namespace Mvc_Projem.Controllers
{
    public class LoginController : Controller
    {
        private readonly Context _context;

        public LoginController(Context context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult GirisYap()
        {
            return View();
        }

        public async Task<IActionResult> GirisYap(Admin admin)
        {
            var bilgiler = _context.Admins.FirstOrDefault(x => x.Kullanici == admin.Kullanici && x.Sifre == admin.Sifre);

            if (bilgiler != null) // bilgiler bos degilse icerdeki islemleri gerceklestirir.
            {
                // talepler
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, admin.Kullanici) // turu,value degeri
                };

                var userIdentity = new ClaimsIdentity(claims, "Login"); //talebin kimligi / claimsten gelen deger,Authentication'dan gelen deger.

                ClaimsPrincipal principal = new ClaimsPrincipal(userIdentity); // birden çok talebi karsılamak icin kullanılır.

                await HttpContext.SignInAsync(principal); // tanımlanan talebin nesnesini gondeririz!

                return RedirectToAction("Index", "Personel");
            }
            return View();
        }
    }
}

Mvc-Projem/Controllers/PersonelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mvc_Projem.Models;

namespace Mvc_Projem.Controllers
{
    public class PersonelController : Controller
    {
        Context context = new Context();

        [Authorize] // yetkisi olanlar giris yapıcak!
        public IActionResult Index() // personelleri listeler.
        {
            var degerler = context.Personels.Include(x => x.Birim).ToList(); // birim sınıfını da dahil et !

            return View(degerler);
        }

        [HttpGet]
        public IActionResult YeniPersonel() // olmadı
        {
            List<SelectListItem> degerler = (from x in context.Birims.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = x.BirimAd, // kullanıcının gordugu
                                                 Value = x.Id.ToString() // yazılımcının gordugu
                                             }).ToList();
            ViewBag.deger = degerler;
            return View();
        }

        [HttpPost]
        public IActionResult YeniPersonel(Personel personel)
        {
            var prs = context.Birims.FirstOrDefault(x => x.Id == personel.BirimId);
            personel.Birim = prs;
            context.Personels.Add(personel);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult PersonelSil(int id) // silme işlemini görmüyor.
        {
            var sil = context.Personels.Find(id);
            context.Personels.Remove(sil);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult PersonelGetir(int id)
        {
            var personel = context.Personels.Find(id);
            return View("PersonelGetir", personel);
        }

        public IActionResult PersonelGuncelle(Personel personel)
        {
            var dep = context.Personels.Find(personel.PersonelId);

            dep.Ad = personel.Ad;
            context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

Mvc-Projem/Views/Birim/BirimDetay.cshtml
@model List<Personel>
@{
    ViewData["Title"] = "BirimDetay";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}


<br />
<h2>Departman : @ViewBag.brm</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Şehir</th>


    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.PersonelId</td>
            <td>@item.Ad</td>
            <td>@item.Soyad</td>
            <td>@item.Sehir</td>
        </tr>

    }
</table>

Mvc-Projem/Views/Birim/BirimGetir.cshtml
@model Birim
@{
    ViewData["Title"] = "BirimGetir";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}


<form asp-action="BirimGuncelle" asp-controller="Birim" method="post">
    <div class="col-md-5W">

        <div class="form-group">
            <b> <label>Departman Id</label></b>
            <input asp-for="Id" type="text" class="form-control" />
        </div>
        <br />
        <div class="form-group">
            <b> <label asp-for="BirimAd">Departman Adı</label></b>
            <input asp-for="BirimAd" type="text" class="form-control" />
        </div>
    </div>
    <br />
    <div class="form-group">
        <button type="submit" class="btn btn-warning">Birim Güncelle</button>
    </div>
</form>

Mvc-Projem/Views/Birim/Index.cshtml
@model List<Birim>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Birim Adı</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
        <th>Sil</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.BirimAd</td>
            <td>
                <a asp-action="BirimGetir" asp-controller="Birim" asp-route-id="@item.Id" class="btn btn-success">Güncelle</a>
            </td>

            <td>
                <a asp-action="BirimDetay" asp-controller="Birim" asp-route-id="@item.Id" class="btn btn-warning">Detaylar</a>
            </td>
            <td>
                <a asp-action="BirimSil" asp-controller="Birim" asp-route-id="@item.Id" class="btn btn-danger">Sil</a>
            </td>
        </tr>
    }
</table>
<a class="btn btn-primary" asp-action="YeniBirim" asp-controller="Birim">Yeni Birim Ekle</a>

Mvc-Projem/Views/Birim/YeniBirim.cshtml
@model Birim
@{
    ViewData["Title"] = "YeniBirim";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<br />
<div class="row">

    <form method="post">
        <div class="col-md-5W">

            <div class="form-group">
                <b> <label>Birim Adı</label></b>
                <input asp-for="BirimAd" type="text" class="form-control" />
            </div>
        </div>
        <br />
        <div class="form-group">
            <button type="submit" class="btn btn-info">Birim Ekle</button>
        </div>
    </form>

</div>

Mvc-Projem/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Mvc-Projem/Views/Login/GirisYap.cshtml
@model Admin

@{
    Layout = null;
}


<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
    <title>MVC Proje</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Blend  Login Form template Responsive, Login form web template,Flat Pricing tables,Flat Drop downs  Sign up Web Templates, Flat Web Templates, Login sign up Responsive web template, SmartPhone Compatible web template, free WebDesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- Custom Theme files -->
    <link href="~/web/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/web/css/font-awesome.css" rel="stylesheet"> <!-- Font-Awesome-Icons-CSS -->
    <!-- //Custom Theme files -->
    <!-- web font -->
    <link href="//fonts.googleapis.com/css?family=Vollkorn+SC:400,600,700,900&amp;subset=cyrillic,cyrillic-ext,latin-ext,vietnamese" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Acme" rel="stylesheet">
    <!-- //web font -->
</head>
<body>
    <!-- main -->
    <div class="main">
        <h1>Mvc Core Giriş Formu</h1>
        <div class="main-w3lsrow">
            <!-- login form -->
            <div class="login-form login-form-left">
                <div class="agile-row">
                    <h2>Giriş Paneli</h2>
                    <div class="login-agileits-top">
                        <form action="#" method="post">
                            <p>Kullanıcı Adınız</p>
                            <input type="text" class="name" name="Kullanici" required="" />
                            <p>Şifre</p>
                            <input type="password" class="password" name="Sifre" required="" />
                            <label class="anim">
                                <input type="checkbox" class="checkbox">
                                <span> Beni Hatırla</span>
                            </label>
                            <input type="submit" value="Giriş Yap">
                        </form>
                    </div>
                    <div class="login-agileits-bottom">
                        <h6><a href="#">Şifremi Unuttum !</a></h6>
                    </div>
                    <div class="login-agileits-bottom1">
                        <h3>Veya</h3>

                    </div>
                    <div class="social_icons agileinfo">
                        <ul class="top-links">
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                        </ul>
                    </div>

                </div>
            </div>
        </div>
        <!-- copyright -->
        <div class="copyright">
            <p> © 2024 Blend  Login Form. Tüm Hakları Saklıdır | Design by <a href="http://w3layouts.com/" target="_blank">W3layouts</a></p>
        </div>
        <!-- //copyright -->
    </div>
    <!-- //main -->
</body>
</html>

Mvc-Projem/Views/Personel/Index.cshtml
@model List<Personel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Şehir</th>
        <th>Departman</th>
        <th>Güncelle</th>
        <th>Sil</th>
        @* <th>Detaylar</th> *@
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.PersonelId</td>
            <td>@item.Ad</td>
            <td>@item.Soyad</td>
            <td>@item.Sehir</td>
            <td>@item.BirimId</td>
            <td>
                <a asp-action="PersonelGetir" asp-controller="Personel" asp-route-id="@item.PersonelId" class="btn btn-success">Güncelle</a>
            </td>
            <td>
                <a asp-action="PersonelSil" asp-controller="Personel" asp-route-id="@item.PersonelId" class="btn btn-danger">Sil</a>
            </td>
        </tr>
    }
</table>
<a class="btn btn-primary" asp-action="YeniPersonel" asp-controller="Personel">Yeni Personel Ekle</a>

Mvc-Projem/Views/Personel/PersonelGetir.cshtml
@model Personel
@{
    ViewData["Title"] = "PersonelGetir";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<form asp-action="PersonelGuncelle" asp-controller="Personel" method="post">
    <div class="col-md-5W">

        <div class="form-group">
            <b> <label>Departman Id</label></b>
            <input asp-for="PersonelId" type="text" class="form-control" />
        </div>
        <br />
        <div class="form-group">
            <b> <label asp-for="Ad">Personel Adı</label></b>
            <input asp-for="Ad" type="text" class="form-control" />
        </div>
        <br />
        <div class="form-group">
            <b> <label asp-for="Soyad">Personel Soyadı</label></b>
            <input asp-for="Soyad" type="text" class="form-control" />
        </div>
        <br />
        <div class="form-group">
            <b> <label asp-for="Ad">Sehir</label></b>
            <input asp-for="Sehir" type="text" class="form-control" />
        </div>

    </div>
    <br />
    <div class="form-group">
        <button type="submit" class="btn btn-warning">Personel Güncelle</button>
    </div>
</form>

Mvc-Projem/Views/Personel/YeniPersonel.cshtml
@model Personel
@{
    ViewData["Title"] = "YeniPersonel";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<br />
<div class="row">

    <form method="post">
        <div class="col-md-5W">

            <div class="form-group">
                <b> <label>Personel Adı</label></b>
                <input asp-for="Ad" type="text" class="form-control" />
            </div>

            <div class="form-group">
                <b> <label>Personel Soyadı</label></b>
                <input asp-for="Soyad" type="text" class="form-control" />
            </div>

            <div class="form-group">
                <b> <label>Şehir</label></b>
                <input asp-for="Sehir" type="text" class="form-control" />
            </div>

            <div class="form-group">
                <b> <label>Birim Adı</label></b>
                <select asp-for=BirimId asp-items="@ViewBag.deger"  type="text" class="form-select" >
                    <option disabled selected>-Birim Seçiniz-

                    </option>
                </select>
            </div>
        </div>
        <br />
        <div class="form-group">
            <button type="submit" class="btn btn-info">Personel Ekle</button>
        </div>
    </form>

</div>

Mvc-Projem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mvc_Projem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mvc_Projem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mvc_Projem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Mvc_Projem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Mvc-Projem/Views/Shared/_TestLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<title>MVC Projem</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">

<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f8f9fa; /* Açık gri arka plan */
    }

    .sidebar {
        height: 100vh;
        position: fixed;
        top: 0;
        left: 0;
        width: 15%;
        background-color: #fdfdfd; /* Kırık beyaz sidebar */
        box-shadow: 2px 0 5px rgba(0, 0, 0, 0.1); /* Hafif gölge */
        border-right: 1px solid #dee2e6; /* İnce kenarlık */
    }

        .sidebar h3 {
            font-size: 1.5rem;
            color: #495057; /* Soluk koyu gri başlık */
            padding: 15px 10px;
        }

    .list-group {
        background-color: #fdfdfd; /* Kırık beyaz menü arka planı */
    }

    .list-group-item {
        background-color: #fdfdfd; /* Kırık beyaz menü elemanları */
        color: #495057; /* Soluk koyu gri metin */
        border: none; /* Kenarlıkları kaldır */
    }

        .list-group-item:hover {
            background-color: #e9ecef; /* Hover için açık gri ton */
            color: #212529; /* Daha koyu metin rengi */
        }

    .content {
        margin-left: 17%;
        padding: 30px;
        background-color: #fdfdfd; /* Kırık beyaz içerik alanı */
        border-radius: 8px; /* Hafif yuvarlatılmış köşeler */
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); /* Hafif gölge */
    }

    .navbar-custom {
        padding: 15px 20px;
        background-color: #f8f9fa; /* Açık gri ton */
        color: #495057; /* Soluk koyu gri metin */
        border-bottom: 1px solid #dee2e6; /* İnce alt kenarlık */
    }

    h1 {
        font-size: 1.8rem;
        font-weight: 600;
    }

    .table-container {
        margin-top: 20px;
    }
</style>
<body>

    <!-- Sidebar -->
    <div class="sidebar">
        <h3 class="p-3">Menüler</h3>
        <div class="list-group">
            <a asp-controller="Birim" asp-action="Index" class="list-group-item list-group-item-action">Birimler</a>
            <a asp-controller="Personel" asp-action="Index" class="list-group-item list-group-item-action">Personeller</a>
            <a href="#" class="list-group-item list-group-item-action">Hakkımızda</a>
            <a asp-controller="Login" asp-action="GirisYap" class="list-group-item list-group-item-action">Çıkış</a>
        </div>
    </div>

    <!-- Page Content -->
    <div class="content">
        <!-- Navbar -->
        <div class="navbar-custom">
            <h1>Asp.Net Core Mvc Proje Geliştirme</h1>
        </div>

        <!-- Main Content -->
        <div class="table-container">
            @RenderBody()
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

@* @{
    Layout = null;
}

<!DOCTYPE html>
<html>
<title>MVC Projem</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet">
<body>

    <!-- Sidebar -->
    <div class="w3-sidebar w3-light-grey w3-bar-block" style="width:15%">
        <h3 class="w3-bar-item">Menüler</h3>
        <a asp-controller="Birim" asp-action="Index" class="w3-bar-item w3-button">Birimler</a>
        <a asp-controller="Personel" asp-action="Index" class="w3-bar-item w3-button">Personeller</a>
        <a href="#" class="w3-bar-item w3-button">Hakkımızda</a>
        <a href="#" class="w3-bar-item w3-button">Çıkış</a>
    </div>

    <!-- Page Content -->
    <div style="margin-left:15%">

        <div class="w3-container w3-teal">
            <h1>Asp.Net Core Mvc Proje Geliştirme</h1>
        </div>

        @RenderBody()

    </div>

</body>
</html> *@